# Generated by Django 5.2.6 on 2025-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=16)),
                ('user', models.TextField()),
                ('user_iv', models.CharField(max_length=24)),
                ('content', models.TextField()),
                ('iv', models.CharField(max_length=24)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NukedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=16, unique=True)),
                ('nuked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-nuked_at'],
            },
        ),
    ]
