[package]
name = "NanoChat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
